# Generated by Django 3.0.6 on 2020-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InwardRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferenceNumber', models.IntegerField()),
                ('ReferenceRecievedDate', models.DateField()),
                ('LatterDetails', models.CharField(max_length=150)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('ReferenceType', models.CharField(choices=[('Local', 'Local'), ('Govt', 'Govt')], max_length=10)),
                ('ReferenceDate', models.DateField()),
                ('RecievedFrom', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('TypeOfReference', models.CharField(choices=[('Tahasildar', 'Tahasildar'), ('CollectorOffice', 'Collector Office')], max_length=20)),
                ('Priority', models.CharField(choices=[('1Day', '1Day'), ('2Day', '2Day'), ('3Day', '3Day')], max_length=20)),
                ('AttachedDocuments', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPurchaseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketName', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Ammount', models.IntegerField()),
                ('PurchaseDate', models.DateField()),
            ],
        ),
    ]
