# Generated by Django 3.0.6 on 2020-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='createUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_no', models.BigIntegerField()),
                ('employee_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
