# Generated by Django 3.0.6 on 2020-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0005_remove_createuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
    ]
