# Generated by Django 3.0.6 on 2020-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0013_inwardregistry_ticketpurchaseinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardregistry',
            name='Desk_id',
            field=models.CharField(default=1, max_length=20, verbose_name='Desk_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='AttachedDocuments',
            field=models.FileField(upload_to='docs', verbose_name='Attached Documents'),
        ),
    ]
