# Generated by Django 3.0.6 on 2020-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0014_auto_20200601_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardregistry',
            name='Departments',
            field=models.CharField(choices=[('desc1', 'desc1'), ('desc2', 'desc2'), ('desc3', 'desc3')], default=1, max_length=20, verbose_name='Department'),
            preserve_default=False,
        ),
    ]
