# Generated by Django 3.0.6 on 2020-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0015_inwardregistry_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='Departments',
            field=models.CharField(choices=[('desc1', 'desc1'), ('desc2', 'desc2'), ('desc3', 'desc3')], max_length=20, verbose_name=''),
        ),
    ]
