# Generated by Django 3.0.6 on 2020-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0017_auto_20200601_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardregistry',
            name='user_id',
            field=models.CharField(default=1, max_length=20, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='Departments',
            field=models.CharField(choices=[('desk1', 'desk1'), ('desk4', 'desk4'), ('desk5', 'desk5'), ('desk6', 'desk6')], max_length=20, verbose_name=''),
        ),
    ]
