# Generated by Django 3.0.6 on 2020-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0018_auto_20200601_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
