# Generated by Django 3.0.6 on 2020-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0024_auto_20200602_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardregistry',
            name='user_id',
            field=models.CharField(default='0000000', max_length=20, verbose_name='user_id'),
        ),
    ]
