# Generated by Django 3.0.6 on 2020-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0025_auto_20200602_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardregistry',
            name='AttachedDocuments',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Attached Documents'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='Departments',
            field=models.CharField(choices=[('user-1', 'user-1'), ('user-2', 'user-2'), ('user-3', 'user-3'), ('user-4', 'user-4')], max_length=20, verbose_name=''),
        ),
    ]
