# Generated by Django 3.0.6 on 2020-06-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0027_auto_20200608_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwardregistry',
            old_name='AttachedDocuments',
            new_name='docsAttch',
        ),
    ]
