# Generated by Django 3.0.6 on 2020-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0028_auto_20200608_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardregistry',
            name='ReferenceNumber',
            field=models.IntegerField(unique=True, verbose_name='Reference Number'),
        ),
    ]
