# Generated by Django 3.0.6 on 2020-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0029_auto_20200608_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardregistry',
            name='ReferenceNumber',
            field=models.IntegerField(verbose_name='Reference Number'),
        ),
    ]
