# Generated by Django 3.0.6 on 2020-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0030_auto_20200608_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardregistry',
            name='status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='Address',
            field=models.CharField(default='Pune', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='EmailId',
            field=models.EmailField(default='xyz@gmail.com', max_length=254, verbose_name='E-mail ID'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='LatterDetails',
            field=models.CharField(default='xyz', max_length=150, verbose_name='Latter Details'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='MobileNumber',
            field=models.CharField(default='8766518297', max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='RecievedFrom',
            field=models.CharField(default='user-1', max_length=100, verbose_name='Recieved From'),
        ),
        migrations.AlterField(
            model_name='inwardregistry',
            name='ReferenceNumber',
            field=models.IntegerField(default='0000001', verbose_name='Reference Number'),
        ),
    ]
