# Generated by Django 3.0.6 on 2020-06-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0031_auto_20200609_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InwardRegistry',
        ),
    ]
