# Generated by Django 3.0.6 on 2020-06-09 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0032_delete_inwardregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecRefNumber', models.IntegerField(default='0000001', verbose_name='Recieved Reference Number')),
                ('LttrRecDate', models.DateField(default=datetime.datetime.now, verbose_name='Latter Recieved Date')),
                ('LatterDetails', models.CharField(default='xyz', max_length=150, verbose_name='Latter Details')),
                ('EmailId', models.EmailField(default='xyz@gmail.com', max_length=254, verbose_name='E-mail ID')),
                ('Address', models.CharField(default='Pune', max_length=200, verbose_name='Address')),
                ('TypeOfReference', models.CharField(choices=[('Internal', 'Internal'), ('Govt', 'Govt')], max_length=10, verbose_name='Type Of Reference')),
                ('RecDate', models.DateField(default=datetime.datetime.now, verbose_name='Reference Date')),
                ('RecFrom', models.CharField(default='user-1', max_length=100, verbose_name='Recieved From')),
                ('MobileNumber', models.CharField(default='8766518297', max_length=10, verbose_name='Mobile Number')),
                ('RecFromDept', models.CharField(choices=[('Tahasildar', 'Tahasildar'), ('CollectorOffice', 'Collector Office')], max_length=20, verbose_name='Received From Department')),
                ('Priority', models.CharField(choices=[('1Day', '1Day'), ('2Day', '2Day'), ('3Day', '3Day')], max_length=20, verbose_name='Priority')),
                ('docsAttch', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Attached Documents')),
                ('Desk_id', models.CharField(max_length=20, verbose_name='Desk_id')),
                ('users', models.CharField(choices=[('user-1', 'user-1'), ('user-2', 'user-2'), ('user-3', 'user-3'), ('user-4', 'user-4')], max_length=20, verbose_name='')),
                ('user_id', models.CharField(default='0000000', max_length=20, verbose_name='user_id')),
                ('status', models.BooleanField(default='Unseen')),
            ],
        ),
    ]
