# Generated by Django 3.0.6 on 2020-06-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0033_inwardregistry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InwardRegistry',
            new_name='InwardReg',
        ),
    ]
