# Generated by Django 3.0.6 on 2020-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0034_auto_20200609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardreg',
            name='status',
            field=models.CharField(default='Unseen', max_length=6),
        ),
    ]
