# Generated by Django 3.0.6 on 2020-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0036_remove_inwardreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardreg',
            name='Status',
            field=models.CharField(default='Unseen', max_length=20),
        ),
    ]
