# Generated by Django 3.0.6 on 2020-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0037_inwardreg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardreg',
            name='LatterDetails',
            field=models.TextField(default='xyz', verbose_name='Latter Details'),
        ),
    ]
