# Generated by Django 3.0.6 on 2020-06-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0038_auto_20200609_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPurchaseInformation',
        ),
    ]
