# Generated by Django 3.0.6 on 2020-06-10 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0039_delete_ticketpurchaseinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardreg',
            name='docsAttch',
        ),
        migrations.CreateModel(
            name='InwardDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttchedDate', models.DateField(default=datetime.datetime.now, verbose_name='Document Attached Date')),
                ('DocsAttch', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Attached Documents')),
                ('InwardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TapalAdmin.InwardReg')),
            ],
        ),
    ]
