# Generated by Django 3.0.6 on 2020-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0040_auto_20200610_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarddocs',
            name='user_id',
            field=models.CharField(default='0000000', max_length=20, verbose_name='user_id'),
        ),
    ]
