# Generated by Django 3.0.6 on 2020-06-12 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0041_inwarddocs_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardreg',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Madium', 'Madium'), ('High', 'High')], max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='RecDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Recieved Date'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='RecFromDept',
            field=models.CharField(choices=[('Department1', 'Department1'), ('Department2', 'Department2')], max_length=20, verbose_name='Received From Department'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='RecRefNumber',
            field=models.CharField(default='AIM-0001', max_length=10, verbose_name='Recieved Reference Number'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='TypeOfReference',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10, verbose_name='Type Of Reference'),
        ),
    ]
