# Generated by Django 3.0.6 on 2020-06-15 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0042_auto_20200612_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardreg',
            name='forwardedBy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='LatterDetails',
            field=models.TextField(default='xyz', verbose_name='Letter Details'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='LttrRecDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Letter Recieved Date'),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, verbose_name='Priority'),
        ),
    ]
