# Generated by Django 3.0.6 on 2020-06-16 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0043_auto_20200615_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutwardReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OutwardDate', models.DateField(default=datetime.datetime.now, verbose_name='Outward Date')),
                ('Note', models.TextField(default='xyz', verbose_name='Forwarding Note')),
                ('OutwardTo', models.CharField(max_length=50, verbose_name='Outward To')),
                ('OutwardBy', models.CharField(max_length=20, verbose_name='Outward By')),
                ('OutwardDoc', models.FileField(max_length=20, upload_to='', verbose_name='Documents')),
                ('InwardId', models.IntegerField(verbose_name='Inward ID')),
            ],
        ),
    ]
