# Generated by Django 3.0.6 on 2020-06-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0045_auto_20200616_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardreg',
            name='forwardedBy',
        ),
    ]
