# Generated by Django 3.0.6 on 2020-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0046_remove_inwardreg_forwardedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardreg',
            name='History',
            field=models.TextField(default='xyz', verbose_name='History'),
        ),
    ]
