# Generated by Django 3.0.6 on 2020-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0047_outwardreg_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardreg',
            name='Status',
            field=models.CharField(default='Activated', max_length=20),
        ),
        migrations.AlterField(
            model_name='inwardreg',
            name='Status',
            field=models.CharField(default='Activated', max_length=20),
        ),
    ]
