# Generated by Django 3.0.6 on 2020-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0051_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardreg',
            name='Status',
            field=models.BooleanField(default='True'),
        ),
    ]
