# Generated by Django 3.0.6 on 2020-07-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0053_auto_20200708_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardreg',
            name='Status',
        ),
    ]
