# Generated by Django 3.0.8 on 2020-08-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0057_outwardreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
