# Generated by Django 3.0.8 on 2020-08-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0059_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default='dept', max_length=125, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_phno',
            field=models.CharField(max_length=12, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pin',
            field=models.CharField(max_length=6, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
    ]
