# Generated by Django 3.0.8 on 2020-08-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0060_auto_20200817_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default=None, max_length=125, verbose_name='Department Name'),
        ),
    ]
