# Generated by Django 3.0.8 on 2020-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0061_auto_20200817_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default=' ', max_length=125, unique=True, verbose_name='Department Name'),
        ),
    ]
