# Generated by Django 3.0.8 on 2020-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0062_auto_20200818_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=50, null=True, verbose_name='Department'),
        ),
    ]
