# Generated by Django 3.0.8 on 2020-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0065_auto_20200818_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=125, verbose_name='Department Name'),
        ),
    ]
