# Generated by Django 3.0.8 on 2020-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0066_auto_20200818_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default='dept1', max_length=125, verbose_name='Department Name'),
        ),
    ]
