# Generated by Django 3.0.8 on 2020-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0067_auto_20200818_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_name',
        ),
    ]
