# Generated by Django 3.0.8 on 2020-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0068_remove_department_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(default=1, max_length=50, verbose_name='Department'),
            preserve_default=False,
        ),
    ]
