# Generated by Django 3.0.8 on 2020-08-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0069_auto_20200819_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
