# Generated by Django 3.0.8 on 2020-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0070_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=125)),
                ('d_phone', models.CharField(max_length=11)),
                ('d_location', models.CharField(max_length=125)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
