# Generated by Django 3.0.8 on 2020-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0071_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardreg',
            name='currentDept',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=50),
        ),
    ]
