# Generated by Django 3.0.8 on 2020-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0072_auto_20200821_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outwardreg',
            name='Note',
        ),
        migrations.AddField(
            model_name='outwardreg',
            name='Comment',
            field=models.TextField(default='xyz', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='d_location',
            field=models.CharField(max_length=125, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='d_name',
            field=models.CharField(max_length=125, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='d_phone',
            field=models.CharField(max_length=11, verbose_name='Department Phone'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='pin',
            field=models.CharField(max_length=6, verbose_name='Pin'),
        ),
    ]
