# Generated by Django 3.0.8 on 2020-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0073_auto_20200909_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardreg',
            name='OutwardAdd',
            field=models.CharField(default=1, max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outwardreg',
            name='sub',
            field=models.CharField(default=1, max_length=255, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outwardreg',
            name='Comment',
            field=models.TextField(default='xyz', verbose_name='Comment Here'),
        ),
        migrations.AlterField(
            model_name='outwardreg',
            name='OutwardTo',
            field=models.CharField(max_length=100, verbose_name='To'),
        ),
    ]
