# Generated by Django 3.0.8 on 2020-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapalAdmin', '0074_auto_20200910_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardreg',
            name='History',
            field=models.TextField(default='NONE', verbose_name='History'),
        ),
    ]
